num=int(input("Digite um valor:"))
print("{} vezes 1 é {}".format(num, num*1))
print("{} vezes 2 é {}".format(num, num*2))
print("{} vezes 3 é {}".format(num, num*3))
print("{} vezes 4 é {}".format(num, num*4))
print("{} vezes 5 é {}".format(num, num*5))
print("{} vezes 6 é {}".format(num, num*6))
print("{} vezes 7 é {}".format(num, num*7))
print("{} vezes 8 é {}".format(num, num*8))
print("{} vezes 9 é {}".format(num, num*9))
print("{} vezes 10 é {}".format(num, num*10))